[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = ["@openzeppelin=lib/openzeppelin-contracts","@chainlink/contracts/=lib/chainlink-brownie-contracts/contracts/",
    "@solmate=lib/solmate/src",]
ffi = false
fs_permissions = [
    { access = "read", path = "./imgs/" },
    { access = "read", path = "./broadcast" },
    { access = "read", path = "./reports" },
]

[invariant]
runs = 128
depth = 128
fail_on_revert = true
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
